# Generated by Django 4.1.5 on 2023-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_id',
            field=models.IntegerField(default=8014970423521, unique=True),
        ),
    ]
